ALTER TABLE usuarios ALTER COLUMN telefone DROP NOT NULL;
ALTER TABLE usuarios ALTER COLUMN cpf DROP NOT NULL;
ALTER TABLE usuarios ALTER COLUMN genero DROP NOT NULL;
ALTER TABLE usuarios ALTER COLUMN data_nascimento DROP NOT NULL;
ALTER TABLE usuarios ALTER COLUMN endereco DROP NOT NULL;
